version: "3.7"
services:
  humanoid:
    image: phtcosta/humanoid:1.0
    container_name: humanoid
    ports:
      - 50405:50405
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -s -X POST -H 'Content-Type: application/json' -d '{\"history_view_trees\": {}, \"history_events\": [], \"possible_events\": [], \"screen_res\": []}' http://localhost:50405"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://127.0.0.1:50405"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
  rv01:
    image: phtcosta/rvandroid:0.0.1
    container_name: rv01
    environment:
      - RV_REPETITIONS=${REPETITIONS}
      - RV_TIMEOUTS=${TIMEOUTS}
      - RV_TOOLS=${TOOLS}
      - RV_HUMANOID_URL=${HUMANOID_URL}
      - RV_NO_WINDOW=${NO_WINDOW}
      - RV_JCA_SPEC=${JCA_SPEC}
    volumes:
      - ./01/apks:/opt/rvsec/rv-android/apks
      - ./01/instrumented:/opt/rvsec/rv-android/out
      - ./01/results:/opt/rvsec/rv-android/results
    devices:
      - /dev/kvm:/dev/kvm
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    depends_on:
      - humanoid
  rv02:
    image: phtcosta/rvandroid:0.0.1
    container_name: rv02
    environment:
      - RV_REPETITIONS=${REPETITIONS}
      - RV_TIMEOUTS=${TIMEOUTS}
      - RV_TOOLS=${TOOLS}
      - RV_HUMANOID_URL=${HUMANOID_URL}
      - RV_NO_WINDOW=${NO_WINDOW}
      - RV_JCA_SPEC=${JCA_SPEC}
      # - RV_DELAY=15
    volumes:
      - ./02/apks:/opt/rvsec/rv-android/apks
      - ./02/instrumented:/opt/rvsec/rv-android/out
      - ./02/results:/opt/rvsec/rv-android/results
    devices:
      - /dev/kvm:/dev/kvm
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    depends_on:
      - humanoid
  rv03:
    image: phtcosta/rvandroid:0.0.1
    container_name: rv03
    environment:
      - RV_REPETITIONS=${REPETITIONS}
      - RV_TIMEOUTS=${TIMEOUTS}
      - RV_TOOLS=${TOOLS}
      - RV_HUMANOID_URL=${HUMANOID_URL}
      - RV_NO_WINDOW=${NO_WINDOW}
      - RV_JCA_SPEC=${JCA_SPEC}
      # - RV_DELAY=30
    volumes:
      - ./03/apks:/opt/rvsec/rv-android/apks
      - ./03/instrumented:/opt/rvsec/rv-android/out
      - ./03/results:/opt/rvsec/rv-android/results
    devices:
      - /dev/kvm:/dev/kvm
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    depends_on:
      - humanoid
  rv04:
    image: phtcosta/rvandroid:0.0.1
    container_name: rv04
    environment:
      - RV_REPETITIONS=${REPETITIONS}
      - RV_TIMEOUTS=${TIMEOUTS}
      - RV_TOOLS=${TOOLS}
      - RV_HUMANOID_URL=${HUMANOID_URL}
      - RV_NO_WINDOW=${NO_WINDOW}
      - RV_JCA_SPEC=${JCA_SPEC}
      # - RV_DELAY=45
    volumes:
      - ./04/apks:/opt/rvsec/rv-android/apks
      - ./04/instrumented:/opt/rvsec/rv-android/out
      - ./04/results:/opt/rvsec/rv-android/results
    devices:
      - /dev/kvm:/dev/kvm
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    depends_on:
      - humanoid
  rv05:
    image: phtcosta/rvandroid:0.0.1
    container_name: rv05
    environment:
      - RV_REPETITIONS=${REPETITIONS}
      - RV_TIMEOUTS=${TIMEOUTS}
      - RV_TOOLS=${TOOLS}
      - RV_HUMANOID_URL=${HUMANOID_URL}
      - RV_NO_WINDOW=${NO_WINDOW}
      - RV_JCA_SPEC=${JCA_SPEC}
      # - RV_DELAY=60
    volumes:
      - ./05/apks:/opt/rvsec/rv-android/apks
      - ./05/instrumented:/opt/rvsec/rv-android/out
      - ./05/results:/opt/rvsec/rv-android/results
    devices:
      - /dev/kvm:/dev/kvm
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
    depends_on:
      - humanoid
