#!/usr/bin/env python
"""
Domain models for RV-Android data processing.

This module provides core data structures for representing runtime verification
experiment data, including APK metadata, execution logs, and method information.

### Architectural Overview:
The module uses dataclasses for type-safe data representation across the analysis
pipeline. Models are organized by their primary role: execution logs (RvCoverageLog,
RvErrorLog), application metadata (App, Method), and logcat file organization
(LogcatFile). Enums define experiment and specification types.

### Key Architectural Decisions:
- **Dataclass-Based Design**: Uses Python dataclasses for compile-time type checking
- **Custom Equality/Hashing**: RvErrorLog and RvCoverageLog define __eq__ and __hash__ to enable set-based deduplication
- **Inner Class Normalization**: Stores both original (AspectJ) and normalized class names for signature matching
- **Optional Metrics**: Extends coverage logs with MOP-awareness flags for analysis correlation

### Role in the System:
- Represents runtime verification data collected from logcat
- Provides type-safe containers for coverage and error information
- Enables data pipeline integration between parsers and generators
- Supports deduplication and matching across instrumentation boundaries

### Integration Points:
- Input: Logcat files parsed by exp02_parser and exp01_parser modules
- Output: Data structures consumed by generators (coverage.py) and processors
- Used across batch_generator, reachability, and package_detector modules
"""

from dataclasses import dataclass
from typing import Optional

from enum import Enum


class ExperimentType(Enum):
    """Identifies experiment configuration version and logcat format."""
    EXP01 = 1  # Logcat without timestamps
    EXP02 = 2  # Logcat with timestamps


class SpecType(Enum):
    """Identifies the specification domain for a given experiment."""
    JCA = 1      # JCA cryptographic API specifications
    GENERIC = 2  # Generic Java API specifications

@dataclass
class LogcatFile:
    """Represents a logcat file from a single execution.

    Stores metadata about logcat output from one execution configuration
    (APK + tool + repetition + timeout).
    """
    apk: str           # APK identifier
    repetition: int    # Repetition number (1-3 per tool/timeout combination)
    timeout: int       # Execution timeout in seconds
    tool: str          # UI automation tool used (e.g., humanoid, monkey)
    file_path: str     # Absolute path to logcat file
    file_name: str     # Logcat file name (format: apk__rep__timeout__tool.logcat)
    size_bytes: float  # File size in bytes

@dataclass
class Method:
    """Represents a method from static analysis with reachability and MOP information.

    Derived from .methods files generated by the static analysis pipeline.
    Includes reachability status and MOP-awareness flags for correlation with
    runtime coverage data.
    """
    class_name: str              # Fully qualified class name
    is_activity: bool            # True if class extends Android Activity
    name: str                    # Method name
    parameters: str              # Parameter types in parentheses: (Type1,Type2)
    signature: str               # Full signature: method_name(Type1,Type2)
    reachable: bool              # Reachable from Android entrypoints (static analysis)
    reaches_mop: bool            # Reaches MOP methods directly or indirectly
    directly_reaches_mop: bool   # Directly calls MOP-monitored methods

@dataclass
class App:
    """Represents an APK file with package and experiment metadata.

    Tracks APK availability in different experiments and resolves package
    name discrepancies between manifest and actual code package.
    """
    file_name: str         # APK filename
    file_path: str         # Path to APK file
    exp01: bool            # Available for Experiment 1 (JCA specs)
    exp02: bool            # Available for Experiment 2 (Generic specs)
    manifest_package: str  # Package name from AndroidManifest.xml
    detected_package: str  # Package detected from DEX class paths (may differ)


@dataclass
class RvErrorLog:
    """Represents a runtime verification violation detected during execution.

    Stores property violation information from logcat parsing, including
    execution context (APK, tool, timeout) and violation details (spec, method,
    message). Implements custom equality for set-based deduplication.

    ### Role in the System:
    - Captures MOP violations from logcat output
    - Enables duplicate removal via set operations
    - Supports CSV export for violation analysis
    """
    apk: str                    # APK identifier
    rep: int                    # Repetition number
    timeout: int                # Execution timeout in seconds
    tool: str                   # UI automation tool used
    time: Optional[float]       # Logcat timestamp in seconds (Experiment 2 only)
    spec: str                   # Specification name (e.g., KeyStore_UpdateAuth)
    class_name: str             # Normalized class name (e.g., TabLayout.Tab)
    original_class_name: str    # Original AspectJ class name (e.g., TabLayout$Tab)
    method: str                 # Method name where violation occurred
    message: str                # Full violation message from logcat
    unique_msg: str             # Normalized message for deduplication

    def __hash__(self) -> int:
        """
        Compute hash for set-based deduplication.

        Uses execution context and violation identity (class, method, unique message)
        for hash computation, enabling duplicate detection across multiple logcat
        parses.

        Returns:
            Hash value based on (apk, rep, timeout, tool, class_name, method, unique_msg).
        """
        return hash((
            self.apk, self.rep, self.timeout, self.tool,
            self.class_name, self.method, self.unique_msg
        ))

    def __eq__(self, other: object) -> bool:
        """
        Compare two error logs for deduplication.

        Two violations are considered identical if they occur in the same execution
        (apk, rep, timeout, tool) at the same method with the same violation type
        (unique_msg). Time of occurrence is not included in equality.

        Args:
            other: Object to compare with (should be RvErrorLog).

        Returns:
            True if logs represent the same violation in the same execution context.
        """
        if not isinstance(other, RvErrorLog):
            return False

        return (
            self.apk == other.apk and
            self.rep == other.rep and
            self.timeout == other.timeout and
            self.tool == other.tool and
            self.class_name == other.class_name and
            self.method == other.method and
            self.unique_msg == other.unique_msg
        )

    def to_dict(self) -> dict:
        """
        Convert error log to dictionary representation.

        Returns:
            Dictionary with keys matching CSV column names for export.
        """
        return {
            "apk": self.apk,
            "rep": self.rep,
            "timeout": self.timeout,
            "tool": self.tool,
            "time": self.time,
            "spec": self.spec,
            "class": self.class_name,
            "method": self.method,
            "message": self.message,
            "unique_msg": self.unique_msg
        }


@dataclass
class RvCoverageLog:
    """Represents a method execution recorded during runtime verification.

    Stores method execution information from logcat parsing, including execution
    context (APK, tool, timeout) and method details (class, signature). Includes
    optional MOP-awareness metrics from static analysis. Implements custom equality
    for set-based deduplication.

    ### Role in the System:
    - Captures runtime method executions from logcat output
    - Enables duplicate removal via set operations
    - Correlates with static analysis .methods files for coverage metrics
    - Supports CSV export and coverage analysis

    ### Key Features:
    - Stores both AspectJ (original) and normalized class/signature formats
    - Optional MOP-awareness flags: direct_use, reachability, transitive reach
    - Time-aware for correlation with violation timestamps
    """
    apk: str                         # APK identifier
    rep: int                         # Repetition number
    timeout: int                     # Execution timeout in seconds
    tool: str                        # UI automation tool used
    time: Optional[float]            # Logcat timestamp in seconds (Experiment 2 only)
    class_name: str                  # Normalized class name (e.g., TabLayout.Tab)
    original_class_name: str         # Original AspectJ class name (e.g., TabLayout$Tab)
    method: str                      # Method name
    signature: str                   # Normalized method signature from static analysis
    original_signature: str          # Original AspectJ method signature
    # MOP-awareness flags from .methods static analysis
    cov_directly_use_mop: Optional[bool] = None  # Directly calls MOP-monitored methods
    cov_use_mop: Optional[bool] = None           # Reaches MOP methods directly or indirectly
    cov_reachable: Optional[bool] = None         # Marked reachable from Android entrypoints

    def __hash__(self) -> int:
        """
        Compute hash for set-based deduplication.

        Uses execution context and method identity (class, method, signature) for
        hash computation, enabling duplicate detection across multiple logcat parses.

        Returns:
            Hash value based on (apk, rep, timeout, tool, class_name, method, signature).
        """
        return hash((
            self.apk,
            self.rep,
            self.timeout,
            self.tool,
            self.class_name,
            self.method,
            self.signature
        ))

    def __eq__(self, other: object) -> bool:
        """
        Compare two coverage logs for deduplication.

        Two executions are considered identical if they occur in the same execution
        (apk, rep, timeout, tool) and invoke the same method with the same signature.
        Time of execution is not included in equality.

        Args:
            other: Object to compare with (should be RvCoverageLog).

        Returns:
            True if logs represent the same method execution in the same execution context.
        """
        if not isinstance(other, RvCoverageLog):
            return False

        return (
            self.apk == other.apk and
            self.rep == other.rep and
            self.timeout == other.timeout and
            self.tool == other.tool and
            self.class_name == other.class_name and
            self.method == other.method and
            self.signature == other.signature
        )