"""
Method inventory loader for RV-Android analysis pipeline.

This module provides access to the method inventory generated by static analysis,
including method metadata (class, name, parameters, signature) and reachability
information from Android entrypoints.

### Architectural Overview:
The module implements a CSV reader for .methods files containing static analysis
output. It parses method metadata and reachability indicators, then aggregates
statistics for downstream analysis. This enables coverage comparison between
static analysis (100% baseline) and runtime execution (actual coverage).

### Key Architectural Decisions:
- **CSV-Based Input**: Reads .methods files directly without requiring live APK re-analysis
- **In-Memory Storage**: Maintains method inventory in dictionaries indexed by signature
- **Aggregate Counters**: Computes reachable/MOP-related method counts during load
- **Lazy Method Access**: Provides method lookup by signature without full table scan

### Role in the System:
- Loads static analysis method inventory for each APK
- Provides baseline for coverage calculation
- Enables signature matching between static and runtime data
- Supplies method metadata for cross-reference queries

### Integration Points:
- Input: .methods CSV files from all_methods/ directory
- Dependency: domain.models.Method for method object representation
- Used by: Coverage parsers and analysis scripts for coverage comparison
"""

import csv
import os
from pathlib import Path
from typing import Optional

from domain.models import Method


class AllMethods:
    """
    Loads and provides access to static analysis method inventory from .methods files.

    Parses the CSV output of static analysis containing method metadata and reachability
    information, then provides efficient lookup and aggregate statistics for coverage
    analysis and signature matching.

    ### Architectural Decisions:
    - Validates file existence at initialization to fail fast
    - Loads entire inventory into memory for O(1) signature-based lookup
    - Computes aggregate counts during load to avoid repeated iteration
    - Separates activities from general classes for categorical analysis

    ### Role in the System:
    - Provides baseline method inventory for coverage comparison
    - Enables method metadata lookup by signature
    - Tracks reachability and MOP-relevance statistics
    - Supports cross-referencing between static and runtime data

    ### Key Features:
    - CSV parsing with automatic type conversion (boolean reachability flags)
    - Aggregate statistics: total reachable, reaches_mop, directly_reaches_mop counts
    - Activity class identification and separate tracking
    - Method lookup by fully-qualified signature
    """

    def __init__(self, file_path: Path):
        """
        Initialize the method inventory from a .methods CSV file.

        Validates file existence, loads the CSV content, and computes aggregate
        statistics on method reachability and MOP relevance.

        Args:
            file_path: Path to the .methods CSV file generated by static analysis.

        Raises:
            FileNotFoundError: If the specified file does not exist.
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        self.file_path = file_path
        # APK identifier extracted from filename (e.g., "app.methods" -> "app")
        self.apk = file_path.stem
        # Set of Activity class names
        self.activities = set()
        # Set of all class names
        self.classes = set()
        # Dictionary mapping method signature to Method object
        self.methods: dict[str, Method] = {}
        # Set of all method signatures for fast membership testing
        self.signatures = set()
        # Aggregate counts for statistics
        self.reachable_methods_count = 0
        self.reaches_mop_methods_count = 0
        self.directly_reaches_mop_methods_count = 0
        self._configure()

    def _configure(self) -> None:
        """
        Load and parse the .methods CSV file, populating method inventory and statistics.

        Reads each row from the CSV, creates Method objects with reachability flags,
        and accumulates aggregate counts for statistical analysis.

        ### Implementation Notes:
        - CSV columns expected: class, method, parameters, signature, is_activity,
          reachable, reaches_mop, directly_reaches_mop
        - Boolean fields are converted from "true"/"false" strings (case-insensitive)
        - Method signature is constructed as "class.signature" for full qualification
        - Aggregate counts updated for each flag independently
        """
        with open(self.file_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Construct fully-qualified method signature: class.method(parameters)
                method_key = f"{row['class']}.{row['signature']}"

                # Create Method object with all metadata from CSV
                method = Method(
                    class_name=row["class"],
                    name=row["method"],
                    parameters=row["parameters"],
                    signature=method_key,
                    is_activity=row["is_activity"].lower() == "true",
                    reachable=row["reachable"].lower() == 'true',
                    reaches_mop=row["reaches_mop"].lower() == 'true',
                    directly_reaches_mop=row['directly_reaches_mop'].lower() == 'true'
                )

                # Track Activity classes separately for categorical analysis
                if method.is_activity:
                    self.activities.add(method.class_name)
                # Track all classes for cross-reference queries
                self.classes.add(method.class_name)
                # Index method by signature for efficient lookup
                self.methods[method.signature] = method
                self.signatures.add(method.signature)
                # Accumulate statistics on reachability and MOP relevance
                if method.reachable:
                    self.reachable_methods_count += 1
                if method.reaches_mop:
                    self.reaches_mop_methods_count += 1
                if method.directly_reaches_mop:
                    self.directly_reaches_mop_methods_count += 1

    def get_method(self, signature: str) -> Optional[Method]:
        """
        Retrieve method metadata by fully-qualified signature.

        Args:
            signature: Method signature in the form "class.method(parameters)".

        Returns:
            Method object if found, None otherwise.
        """
        return self.methods.get(signature)

    def __str__(self) -> str:
        """
        Return a string representation of this inventory.

        Returns:
            String identifying the APK filename associated with this inventory.
        """
        return f"AllMethods({os.path.basename(self.file_path)})"