#!/usr/bin/env python
"""
Signature normalizer for RV-Android data processing pipeline.

This module provides normalization of method signatures to resolve discrepancies
between static and dynamic representations of inner class parameters.
Specifically, it converts OuterClass.InnerClass notation to OuterClass$InnerClass
in parameter types to match the format generated by static analysis tools.

### Architectural Overview:
Static analysis via Soot generates signatures with dollar notation for inner
classes (e.g., TabLayout$Tab), while dynamic signatures from runtime may use
dot notation (e.g., TabLayout.Tab). This normalizer converts dynamic signatures
to match static signatures by detecting and correcting inner class patterns based
on Java naming conventions (uppercase identifiers indicate classes, lowercase
indicate packages).

### Key Architectural Decisions:
- **Parameter-Only Normalization**: Only normalizes parameter types; method names
  and declaring class names are preserved unchanged
- **Heuristic-Based Detection**: Uses uppercase/lowercase conventions to distinguish
  inner classes (OuterClass.InnerClass) from package hierarchies (java.lang.String)
- **Whitespace Preservation**: Maintains original spacing in parameter lists to
  avoid altering log formats

### Role in the System:
- Converts dynamic method signatures to match static signature format
- Enables accurate matching of runtime execution traces to static method inventory
- Resolves inner class notation discrepancies between AspectJ monitors and static analysis

### Integration Points:
- Consumed by logcat parsers to normalize signatures before matching against .methods files
- Works with runtime coverage logs containing method execution traces
"""

import re
from typing import Optional


class SignatureNormalizer:
    """
    Normalizes method signatures by correcting inner class notation in parameters.

    Converts dynamic method signatures from runtime execution to match static
    analysis format, specifically addressing the discrepancy where AspectJ and
    logcat use dot notation (e.g., TabLayout.Tab) while static tools use dollar
    notation (e.g., TabLayout$Tab) for inner classes.

    ### Architectural Decisions:
    - Normalizes only parameter types in signatures, leaving method names and
      class declarations unchanged
    - Uses uppercase/lowercase heuristics to distinguish inner classes from
      package components in fully-qualified names
    - Preserves original whitespace patterns in parameter lists to maintain
      compatibility with existing log formats

    ### Role in the System:
    - Transforms dynamic signatures to match static signature inventory
    - Enables accurate method matching in coverage and violation analysis
    - Bridges the notation gap between runtime monitors and static analysis tools

    ### Key Features:
    - Parameter list normalization with support for comma and semicolon separators
    - Array notation handling (e.g., TabLayout$Tab[])
    - Nested inner class support (e.g., Outer$Middle$Inner)
    - Package hierarchy preservation (does not convert java.lang.String to java$lang$String)
    """

    def normalize_signature(self, signature: str) -> str:
        """
        Apply inner class corrections to method parameters.

        Normalizes a complete method signature by converting inner class notation
        in parameter types while preserving the method name. Handles both simple
        and complex parameter lists with proper parentheses balance.

        Examples:
            "onTabSelected(TabLayout.Tab)" → "onTabSelected(TabLayout$Tab)"
            "onCreate(android.os.Bundle)" → "onCreate(android.os.Bundle)"

        Args:
            signature: Method signature to normalize

        Returns:
            Normalized signature with inner class corrections in parameters
        """
        if '(' not in signature:
            return signature

        # Find the opening parenthesis
        paren_start = signature.find('(')
        method_part = signature[:paren_start]

        # Extract everything between parentheses
        remaining = signature[paren_start:]
        if not remaining.endswith(')'):
            # If no closing parenthesis, return as-is
            return signature

        # Extract parameter content (without outer parentheses)
        param_content = remaining[1:-1]  # Remove '(' and ')'

        if param_content:
            normalized_params = self.normalize_parameter_list(param_content)
            return f"{method_part}({normalized_params})"
        else:
            # Empty parameters
            return f"{method_part}()"

    def normalize_class_name(self, class_name: str) -> str:
        """
        Normalize inner class notation in class names.

        Converts dot notation to dollar notation for inner classes while
        preserving package hierarchy notation. Handles both simple inner classes
        and nested inner classes including anonymous inner class numbering.

        Examples:
            "com.example.OuterClass.InnerClass" → "com.example.OuterClass$InnerClass"
            "Map.GameFieldPosition$1" → "Map$GameFieldPosition$1"
            "android.os.Bundle" → "android.os.Bundle"

        Args:
            class_name: Class name to normalize

        Returns:
            Normalized class name with inner class corrections
        """
        if '.' not in class_name:
            return class_name

        # Split preserving both . and $ separators
        # Use regex to split but keep separators
        parts = re.split(r'([.$])', class_name)
        # Example: 'Map.GameFieldPosition$1' → ['Map', '.', 'GameFieldPosition', '$', '1']

        result = []
        i = 0

        while i < len(parts):
            if i == 0:
                # First part is always a component
                result.append(parts[i])
                i += 1
            elif parts[i] in ['.', '$']:
                # Found a separator
                sep = parts[i]
                i += 1

                if i < len(parts):
                    next_part = parts[i]
                    prev_part = result[-1] if result else ''

                    # Decide if this should be $ (inner class) or . (package)
                    if self._is_likely_inner_class(prev_part, next_part):
                        result.append('$')  # Force inner class separator
                    else:
                        result.append(sep)  # Keep original separator

                    result.append(next_part)
                    i += 1
            else:
                # Regular component (shouldn't happen with proper split)
                result.append(parts[i])
                i += 1

        return ''.join(result)

    def normalize_parameter_list(self, parameters: str) -> str:
        """
        Normalize parameter list for inner class corrections.

        Processes parameter types in a list separated by commas or semicolons,
        normalizing each type while preserving whitespace patterns in the original list.

        Args:
            parameters: Parameter list (comma or semicolon separated)

        Returns:
            Normalized parameter list with preserved spacing
        """
        if not parameters or not parameters.strip():
            return parameters

        # Handle both comma and semicolon separators
        separator = ';' if ';' in parameters else ','

        param_parts = parameters.split(separator)
        normalized_parts = []

        for i, param in enumerate(param_parts):
            # Preserve leading/trailing whitespace but normalize the type
            stripped_param = param.strip()
            if stripped_param:
                # Apply inner class normalization to each parameter type
                normalized_param = self._normalize_single_parameter(stripped_param)

                # Restore original spacing pattern
                if i == 0:
                    # First parameter - keep original leading space
                    leading_space = param[:len(param) - len(param.lstrip())]
                    trailing_space = param[len(param.rstrip()):]
                    normalized_parts.append(leading_space + normalized_param + trailing_space)
                else:
                    # Subsequent parameters - preserve space after comma
                    if param.startswith(' '):
                        normalized_parts.append(' ' + normalized_param)
                    else:
                        normalized_parts.append(normalized_param)
            else:
                # Empty parameter, keep as-is
                normalized_parts.append(param)

        return separator.join(normalized_parts)

    def _normalize_single_parameter(self, param_type: str) -> str:
        """
        Normalize a single parameter type for inner classes.

        Converts inner class notation while preserving package hierarchies by
        examining identifier case: both parts uppercase indicates an inner class
        relationship (OuterClass.InnerClass → OuterClass$InnerClass), while
        lowercase parts indicate package components (java.lang.String unchanged).

        Examples:
            "TabLayout.Tab" → "TabLayout$Tab" (both uppercase, inner class)
            "View.OnClickListener" → "View$OnClickListener" (both uppercase, inner class)
            "android.os.Bundle" → "android.os.Bundle" (lowercase parts, packages)
            "java.lang.String" → "java.lang.String" (lowercase parts, packages)
            "OuterClass.InnerClass.Deep" → "OuterClass$InnerClass$Deep" (nested)

        Args:
            param_type: Single parameter type

        Returns:
            Normalized parameter type with inner class corrections
        """
        # Handle array notation
        array_suffix = ''
        while param_type.endswith('[]'):
            array_suffix += '[]'
            param_type = param_type[:-2]

        # Apply inner class normalization only if no $ already present
        if '.' in param_type and '$' not in param_type:
            parts = param_type.split('.')
            normalized_parts = []

            # Process parts to identify inner classes vs packages
            for i, part in enumerate(parts):
                if i == 0:
                    # First part is always added as-is
                    normalized_parts.append(part)
                else:
                    previous_part = parts[i-1]

                    # Convert to inner class (using $) only when both parts are uppercase and
                    # the relationship matches an inner class pattern, not a package hierarchy
                    if (self._is_likely_inner_class(previous_part, part)):
                        # Use $ separator for inner class relationship
                        if normalized_parts:
                            normalized_parts[-1] = normalized_parts[-1] + '$' + part
                        else:
                            normalized_parts.append(part)
                    else:
                        # Keep dot separator for package components
                        normalized_parts.append(part)

            param_type = '.'.join(normalized_parts)

        return param_type + array_suffix

    def _is_likely_inner_class(self, outer_part: str, inner_part: str) -> bool:
        """
        Determine if outer.inner represents an inner class vs package.class.

        Uses Java naming conventions to distinguish the two patterns: inner classes
        have both parts starting with uppercase (OuterClass.InnerClass) while
        package hierarchies have lowercase package names (java.lang.String).

        Args:
            outer_part: The part before the dot
            inner_part: The part after the dot

        Returns:
            True if this appears to be an inner class relationship
        """
        if not outer_part or not inner_part:
            return False

        # Both parts must start with uppercase to be inner class
        outer_is_class = outer_part[0].isupper()
        inner_is_class = inner_part[0].isupper()

        if not (outer_is_class and inner_is_class):
            return False

        # Map of known package names (all lowercase) used to filter false positives
        # Only applies when outer_part is also lowercase to avoid case-sensitivity issues
        known_packages = {
            'android', 'java', 'javax', 'com', 'org', 'net', 'io',
            'os', 'lang', 'util', 'content', 'widget', 'app',
            'support', 'design', 'fragment', 'activity', 'graphics',
            'text', 'database', 'preference', 'animation', 'concurrent'
        }

        # Check against known package names only if outer_part is lowercase.
        # This prevents false matches where class names happen to match package names
        # (e.g., "Widget" class should not match "widget" package)
        if outer_part.islower() and outer_part in known_packages:
            return False

        # Heuristic: short lowercase identifiers are likely package components
        if len(outer_part) <= 3 and outer_part.islower():
            return False

        # If both parts start with uppercase and outer is not a known package,
        # treat as inner class relationship
        return True

    def extract_method_name(self, signature: str) -> str:
        """
        Extract method name from a method signature.

        Isolates the method name portion of a signature by splitting at the opening
        parenthesis. Returns the full signature if no parentheses are found.

        Examples:
            "onCreate(android.os.Bundle)" → "onCreate"
            "methodName()" → "methodName"
            "methodName" → "methodName"

        Args:
            signature: Method signature string

        Returns:
            The method name portion of the signature
        """
        if '(' in signature:
            return signature.split('(')[0]
        return signature

    def extract_parameters(self, signature: str) -> str:
        """
        Extract parameter list from a method signature.

        Isolates the parameter portion of a signature by extracting content between
        parentheses. Returns empty string if no parentheses are found or if the
        signature format is invalid.

        Examples:
            "onCreate(android.os.Bundle)" → "android.os.Bundle"
            "methodName(Type1,Type2)" → "Type1,Type2"
            "methodName()" → ""
            "methodName" → ""

        Args:
            signature: Method signature string

        Returns:
            The parameter list without parentheses, or empty string if not found
        """
        if '(' not in signature:
            return ""

        # Extract content between parentheses
        start = signature.find('(')
        end = signature.rfind(')')

        if start != -1 and end != -1 and end > start:
            return signature[start + 1:end]

        return ""

    def create_signature(self, method_name: str, parameters: str) -> str:
        """
        Create a normalized signature from method name and parameters.

        Constructs a complete method signature by combining a method name with
        normalized parameters, ensuring inner class notation is corrected.

        Examples:
            ("onCreate", "android.os.Bundle") → "onCreate(android.os.Bundle)"
            ("onTabSelected", "TabLayout.Tab") → "onTabSelected(TabLayout$Tab)"

        Args:
            method_name: Name of the method
            parameters: Parameter string to normalize and include

        Returns:
            Complete normalized method signature
        """
        normalized_params = self.normalize_parameter_list(parameters)
        return f"{method_name}({normalized_params})"